### PR TITLE
2024.05

### PR DESCRIPTION
**Pull request by Gerry546**
Support for HA May 2024 release.

Biggest challenge here is the new dependency on ISAL via python3-isal.
https://pypi.org/project/isal/

On HA itself there are also complaints (https://github.com/home-assistant/core/issues/116681) as this is a real pain to get installation and compilation working.
I have tried but failed directly so currently I am falling back to an (ugly) direct wheel build.
I will create a ticket for that package and python3-home-assistant-chip-clusters (which has the same problem).

Furthermore I started adding ptest where possible.

Waiting for a patch send to meta-oe to be merged.

### CODE REVIEW

**Comment by bachp** [comment]
@Gerry546 it seems there is a build error from python3-isal can you take a look

**Comment by Gerry546** [comment]
Hmm strange. Sure I'll take a look

**Comment by Gerry546** [comment]
After kicking off a rebuild the build seems to fail at different times and at different places constantly. While I see if there is something fundamentally wrong with the recipes can you take a look at the builder @bachp ? In my private server the build consistently passes.

**Comment by bachp** [comment]
Ok thanks for checking, CI with the gitlab runners is still not reliable unfortunately.

**Pull request merged**
