### PR TITLE
ci: fix dunfell github actions

### PR DESCRIPTION
**Pull request by bachp**
This fixes github actions for the dunfell branch

### CODE REVIEW

**Review by agherzan — APPROVED** [review]

**Review by agherzan — APPROVED** [review]

**Comment by agherzan** [comment]
@bachp friendly ping on this one

**Comment by bachp** [comment]
@agherzan Unfortunatly github actions doesn't work well with yocto builds. I haven't found a reliable way that doesn't run into timeouts all the time. Ideas are welcome

**Comment by bachp** [comment]
@agherzan I have CI working via kas, but it still takes a lot of time. Ideally there would be a way to cache some of the sstate between runs.

**Comment by agherzan** [comment]
@bachp not easy if you use default workers. I'm not sure what setup you have here.

**Comment by moto-timo** [comment]
@bachp I noticed you got a successful build with CDN SSTATE_MIRROR for mickeldore. I was contemplating if the [10GB limit](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#usage-limits-and-eviction-policy) on [cache@vx](https://github.com/actions/cache) would also be enough to help us keep under the dreaded timeout.

**Comment by bachp** [comment]
@moto-timo Unfortunately I'm not happy with the any of the current CI setups I tried.

I haven't tried cache@vx but so far I found that the sstate doesn't fit well with the method of uploading and downloading the cache. As the cache keeps growing.

But you got me thinking about an idea. Maybe a workflow that would work is the following:

1. Download and extract the cache locally to `${SOMEDIR}/sstate` (usually done automatically by caching service).
2. Rename from `${SOMEDIR}/sstate` to `${SOMEDIR}/sstate-prev`
3. Configure yocto to use `${SOMEDIR}/sstate-prev` as SSTATE_MIRROR
4. Uplaod `${SOMEDIR}/sstate` so it is ready for the next run

I haven't tried this yet.

**Comment by bachp** [comment]
Obsolete now

**Pull request closed without merging**
