### PR TITLE
HA upgrade 2023.11.1

### PR DESCRIPTION
**Pull request by Gerry546**
Add support for 2023.11.1
Updated the python script to parse the HA requirements.
Remove python3-pyroute2 as meta-openembedded has a newer version available.

### CODE REVIEW

**Comment by bachp** [comment]
@Gerry546 I think you just force pushed over my change that also runs CI on pull_requests :smile:

**Comment by bachp** [comment]
@Gerry546 please rebase on current main

**Comment by Gerry546** [comment]
Hmm, something might have gone wrong. I shall check it and rebase it on
yours

**Comment by Gerry546** [comment]
Rebased

**Comment by moto-timo** [comment]
@Gerry546 Just out of curiousity, is an upgrade basically "update python3-homeassistant to a new release on pypi and then satisfy all the version upgrades and missing deps in the various python3-* recipes"?

**Comment by Gerry546** [comment]
The steps that I perform are essentially:

1. Run the python script in the scripts directory for the next tag. This will give a list of recipes of which the requested version in HA is newer than anything found in either meta-homeassistant, meta-openembedded or poky.
2. Update python3-homeassistant for the new PyPi release, specifically check the requiements file as the base dependency sometimes change as well. 
3. Update all other recipes which are needed.
4. Build it for several architectures in my private server for arm64, x86-64 etc. (Mostly obsolete now I hope thanks to @bachp ).
5. I deploy it on a hardware platform in order to check that it no only compiles, but also actually boots and runs as expected.]

Mostly the intermediate releases (11.1, 11.2 etc.) are quite trivial. However this big releases are sometimes quite some more work.
I am also working on automating the tests if possible (ptests?)

**Pull request merged**
