### PR TITLE
Feature/v2023.4.0

### PR DESCRIPTION
**Pull request by Gerry546**
Updated support for HomeAssistant 2023.4.0.
Suggestion is to add a tag when this is merged so people know which commit supports which version of HA

### CODE REVIEW

**Comment by bachp** [comment]
@Gerry546 please feel free to add a tag.

**Comment by Gerry546** [comment]
@bachp I cannot push a tag to main. Seems I do not have the permission to do so.

**Comment by bachp** [comment]
@Gerry546 Try again now

**Comment by Gerry546** [comment]
Done, works now. Thanks.

**Pull request merged**
