### PR TITLE
Kas rework

### PR DESCRIPTION
**Pull request by bachp**
Rework the kas files to be up to date with current main.

### CODE REVIEW

**Comment by Gerry546** [comment]
Now that this is working I would suggest to also block merging unless it passes the CI

**Comment by bachp** [comment]
@Gerry546 Not yet. I would like to keep it optional for some time to see how if it is stable enough.

**Comment by moto-timo** [comment]
@bachp this is getting useful beyond just homeassistant. Thank you for the efforts!
https://github.com/moto-timo/meta-java/actions/runs/7769377548/job/21188394016 
https://github.com/moto-timo/meta-java/tree/github-ci

**Comment by bachp** [comment]
@moto-timo It's not yet fully stable, it still runs out of memory occasionaly. I need to think how we could improve. Maybe build a smaller container image without kernel.

**Pull request merged**
